# Generated by Django 2.1.7 on 2019-03-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAgenda', models.CharField(max_length=128, verbose_name='Nome Agenda')),
                ('publico', models.BooleanField(blank=True, null=True, verbose_name='Público')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAgendaIn', models.CharField(max_length=128, verbose_name='Nome Agenda')),
                ('publico', models.BooleanField(blank=True, null=True, verbose_name='Público')),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('compromisso', models.CharField(max_length=200, verbose_name='Compromisso')),
                ('horario', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('telefone_celular', models.CharField(blank=True, help_text='Numero de telefone celular no formato (99)99999-9999', max_length=15, null=True, verbose_name='Telefone Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('agendas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agenda.Agenda')),
            ],
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='compromissos',
            field=models.ManyToManyField(to='app_agenda.Compromisso'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='compromissos',
            field=models.ManyToManyField(to='app_agenda.Compromisso'),
        ),
    ]
